# gg — build system
#
# `make`            build for the host with the best available compiler
# `make ape`        build the single-file APE (needs cosmocc)
# `make host`       build a plain host binary (fast iteration)
# `make test`       run the test suite head-less
# `make release`    build bin/gg, bin/gg.exe, bin/gg.com and print checksums
# `make install`    copy into ~/.gg/bin and run `gg active`
#
# cosmocc is the only hard dependency for APE builds; scripts/fetch-cosmocc.sh
# downloads it if you do not have it yet.

COSMOCC   ?= $(shell command -v cosmocc 2>/dev/null || echo /opt/cosmocc/bin/cosmocc)
CC        ?= $(shell command -v cc 2>/dev/null || command -v gcc 2>/dev/null || echo cc)
PYTHON    ?= python3

VERSION   := 0.1.0
BUILD     := build
BIN       := bin

# --- sources ---------------------------------------------------------------
APP_SRC   := src/util.c src/tui.c src/proc.c src/registry.c src/modules.c \
             src/bundle.c src/lua_api.c src/builtins.c src/completion.c src/main.c
LUA_SRC   := $(wildcard vendor/lua/*.c)
EMBED_SRC := $(BUILD)/embedded.c
EXAMPLES  := $(sort $(wildcard examples/*.lua))
EMBED_SPEC := $(foreach f,$(EXAMPLES),mod_$(notdir $(f))=$(f))

CFLAGS    ?= -Os -g0 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers
DEPFLAGS  := -MMD -MP
GG_INC    := -Isrc -Ivendor/lua
LUA_DEFS  := -DLUA_USE_POSIX -DLUA_USE_DLOPEN

# ---------------------------------------------------------------------------
.PHONY: all ape host test release install clean fmt check help

all: host

help:
	@sed -n '2,12p' Makefile

$(BUILD):
	@mkdir -p $(BUILD)

$(EMBED_SRC): tools/embed.sh $(EXAMPLES) | $(BUILD)
	@sh tools/embed.sh $@ $(EMBED_SPEC)

# --- host build (cc) -------------------------------------------------------
HOST_OBJ := $(patsubst %.c,$(BUILD)/host/%.o,$(APP_SRC) $(LUA_SRC)) \
            $(BUILD)/host/embedded.o

host: $(BUILD)/gg-host
$(BUILD)/gg-host: $(HOST_OBJ)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS) -lm

$(BUILD)/host/%.o: %.c $(BUILD)/embedded.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(DEPFLAGS) $(GG_INC) $(LUA_DEFS) -c -o $@ $<

$(BUILD)/host/embedded.o: $(EMBED_SRC)
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(DEPFLAGS) $(GG_INC) -c -o $@ $<

# --- APE build (cosmocc) ---------------------------------------------------
# cosmocc emits a single apolitical executable that runs on linux, macos,
# windows, freebsd, openbsd and netbsd.
APE_OBJ := $(patsubst %.c,$(BUILD)/ape/%.o,$(APP_SRC) $(LUA_SRC)) \
           $(BUILD)/ape/embedded.o

ape: $(BIN)/gg $(BIN)/gg.exe $(BIN)/gg.com

$(BIN)/gg: $(APE_OBJ) | $(BIN)
	$(COSMOCC) $(CFLAGS) -o $@ $(APE_OBJ)
	@rm -f $(BIN)/gg.aarch64.elf $(BIN)/gg.com.dbg

$(BIN)/gg.exe: $(BIN)/gg
	cp -f $< $@
$(BIN)/gg.com: $(BIN)/gg
	cp -f $< $@

$(BUILD)/ape/%.o: %.c $(BUILD)/embedded.c
	@mkdir -p $(dir $@)
	$(COSMOCC) $(CFLAGS) $(DEPFLAGS) $(GG_INC) $(LUA_DEFS) -c -o $@ $<

$(BUILD)/ape/embedded.o: $(EMBED_SRC)
	@mkdir -p $(dir $@)
	$(COSMOCC) $(CFLAGS) $(DEPFLAGS) $(GG_INC) -c -o $@ $<

$(BIN):
	@mkdir -p $(BIN)

release: ape
	@cd $(BIN) && sha256sum gg gg.exe gg.com > SHA256SUMS && cat SHA256SUMS
	@echo
	@echo "built:"
	@for f in $(BIN)/gg $(BIN)/gg.exe $(BIN)/gg.com; do \
	  printf '  %-16s %8s bytes  %s\n' "$$f" "$$(wc -c < $$f)" "$$(sha256sum $$f | cut -c1-16)"; done
	@echo "the same bytes run on linux, macos, windows, bsd — just rename it"

# --- tests -----------------------------------------------------------------
GG ?= $(BUILD)/gg-host

test: host
	@sh tests/run.sh $(GG)
	@python3 tests/pty_test.py $(GG)

test-headless: host
	@sh tests/run.sh $(GG)

# --- install ---------------------------------------------------------------
install: ape
	@mkdir -p $(HOME)/.gg/bin
	@cp -f $(BIN)/gg $(HOME)/.gg/bin/gg
	@chmod +x $(HOME)/.gg/bin/gg
	@$(BIN)/gg active
	@echo "installed — open a new shell and type: gg"

clean:
	rm -rf $(BUILD)

distclean: clean
	rm -f $(BIN)/gg $(BIN)/gg.exe $(BIN)/gg.com

fmt:
	@command -v clang-format >/dev/null && clang-format -i src/*.c src/*.h || \
	  echo "clang-format not installed"

# keep the APE payload honest: check the binary claims the right platforms
check: ape
	@$(BIN)/gg --version
	@GG_PLAIN=1 $(BIN)/gg ls >/dev/null && echo "ape smoke test ok"

# --- header dependencies generated by the compiler --------------------------
# (keep this at the very end: the variables above must be defined first)
-include $(HOST_OBJ:.o=.d) $(APE_OBJ:.o=.d)
