#!/bin/sh
# tools/embed.sh — turn files into a C table so gg stays a single binary.
#
# usage: tools/embed.sh <out.c> [name=]path...
#
# Every file becomes `static const unsigned char embed_<name>[]` and is
# listed in the GG_EMBEDDED[] table.
set -e

out="$1"
shift

if [ -z "$out" ] || [ "$#" -eq 0 ]; then
  echo "usage: tools/embed.sh <out.c> [name=]path..." >&2
  exit 2
fi

tmp="$out.tmp"
{
  printf '/* generated by tools/embed.sh — do not edit by hand */\n'
  printf '#include "gg.h"\n\n'

  for spec in "$@"; do
    case "$spec" in
      *=*) name=${spec%%=*}; path=${spec#*=} ;;
      *)   path=$spec; name=$(basename "$spec") ;;
    esac
    sym=$(printf '%s' "$name" | sed 's/[^A-Za-z0-9_]/_/g')
    bytes=$(od -An -v -tu1 "$path" | tr -s ' \n' ',' | sed -e 's/^,//' -e 's/,$//')
    # a trailing NUL keeps the data usable as a C string as well
    if [ -z "$bytes" ]; then bytes=0; else bytes="$bytes,0"; fi
    printf 'static const unsigned char embed_%s[] = {%s};\n' "$sym" "$bytes"
  done

  printf '\nconst embedded_file GG_EMBEDDED[] = {\n'
  for spec in "$@"; do
    case "$spec" in
      *=*) name=${spec%%=*}; path=${spec#*=} ;;
      *)   path=$spec; name=$(basename "$spec") ;;
    esac
    sym=$(printf '%s' "$name" | sed 's/[^A-Za-z0-9_]/_/g')
    size=$(wc -c < "$path" | tr -d ' ')
    printf '  {"%s", (const char *)embed_%s, %s},\n' "$name" "$sym" "$size"
  done
  printf '};\n'
  printf 'const int GG_EMBEDDED_COUNT = %d;\n' "$#"
} > "$tmp"

mv "$tmp" "$out"
